import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import openapiTS, { astToString } from 'openapi-typescript';

const uiRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const backend = process.env.BACKEND_DIR || path.resolve(uiRoot, '../codeagent-scanner');
const schema = JSON.parse(execFileSync(process.env.PYTHON || 'python3', ['-c', 'import json; from api.app import create_app; print(json.dumps(create_app().openapi()))'], {
  cwd: backend, env: { ...process.env, PYTHONPATH: backend }, encoding: 'utf8', maxBuffer: 10 * 1024 * 1024,
}));
const output = '// Generated by npm run api:generate. Do not edit.\n' + astToString(await openapiTS(schema));
const target = path.join(uiRoot, 'lib/generated/api.d.ts');
if (process.argv.includes('--check')) {
  if (readFileSync(target, 'utf8') !== output) {
    process.stderr.write('API types have drifted. Run npm run api:generate.\n'); process.exitCode = 1;
  } else process.stdout.write('Generated API types match backend OpenAPI.\n');
} else { writeFileSync(target, output); process.stdout.write('Generated lib/generated/api.d.ts\n'); }
