"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useCapabilities, useRun, useRunEvents } from "@/lib/hooks";
import { aiConfig, createProject, errorMessage, modelNames, saveAIConfig, submitScan, testAIConfig } from "@/lib/api-client";
import type { AIConfig, ProviderCheck } from "@/lib/types";
import { TERMINAL } from "@/lib/types";
import { Empty, ErrorNotice, Loading, Shell, Status, Time } from "./shared";
import { ProviderPicker } from "./provider-picker";

const DEFAULTS: AIConfig = { provider: "ollama", model: "", min_severity: "high", max_model_calls: 60, max_total_tokens: 100000, timeout_sec: 900, max_findings: 20, max_context_chars: 60000, max_output_tokens: 4000 };
const BUDGETS = [{ key: "max_model_calls", name: "Maximum model calls", min: 1, max: 200 }, { key: "max_total_tokens", name: "Total token budget", min: 1000, max: 1000000 }, { key: "timeout_sec", name: "Review deadline (seconds)", min: 60, max: 7200 }, { key: "max_findings", name: "Maximum findings", min: 1, max: 100 }, { key: "max_context_chars", name: "Context characters", min: 1000, max: 200000 }, { key: "max_output_tokens", name: "Output tokens per call", min: 256, max: 16000 }] as const;
const SAMPLE = "UEsDBBQAAAAAALdqOV1MkWa2YQAAAGEAAAALAAAAZGVtby9hcHAucHlpbXBvcnQgc3VicHJvY2VzcwoKZGVmIHJ1bl91c2VyX2NvbW1hbmQoY29tbWFuZCk6CiAgICByZXR1cm4gc3VicHJvY2Vzcy5ydW4oY29tbWFuZCwgc2hlbGw9VHJ1ZSkKUEsDBBQAAAAAALdqOV2u+UjEMwAAADMAAAALAAAAZGVtby9hcHAuanNmdW5jdGlvbiBwYXJzZUlucHV0KGlucHV0KSB7IHJldHVybiBldmFsKGlucHV0KTsgfQpQSwMEFAAAAAAAt2o5XRgUTD4RAAAAEQAAABUAAABkZW1vL3JlcXVpcmVtZW50cy50eHRyZXF1ZXN0cz09Mi4xOS4xClBLAQIUAxQAAAAAALdqOV1MkWa2YQAAAGEAAAALAAAAAAAAAAAAAACAAQAAAABkZW1vL2FwcC5weVBLAQIUAxQAAAAAALdqOV2u+UjEMwAAADMAAAALAAAAAAAAAAAAAACAAYoAAABkZW1vL2FwcC5qc1BLAQIUAxQAAAAAALdqOV0YFEw+EQAAABEAAAAVAAAAAAAAAAAAAACAAeYAAABkZW1vL3JlcXVpcmVtZW50cy50eHRQSwUGAAAAAAMAAwC1AAAAKgEAAAAA";
export function ReadinessSummary() {
  const { data, error } = useCapabilities();
  return <section className="panel readiness-summary"><div><p className="eyebrow">WORKSPACE STATUS</p><h2>{error ? "Connection needs attention" : data?.worker_online ? "Worker online" : "Worker offline"}</h2><p className="muted">{data ? `${data.analyzers.filter((tool) => tool.available).length} of ${data.analyzers.length} analyzers available` : "Checking analyzer readiness…"}</p></div><Link className="button secondary" href="/setup">Open setup</Link></section>;
}
function CheckResult({ result }: { result?: ProviderCheck }) {
  if (!result) return <p className="muted">No saved connection test. Saving settings does not contact a model.</p>;
  return <div><div className="verification-states">{[["Configured", result.configured], ["Reachable", result.reachable], ["Schema test passed", result.schema_test_passed]].map(([name, passed]) => <div className="verification-label" key={String(name)}><span>{name}</span><Status value={passed ? "passed" : "not_verified"} /></div>)}</div><p className="field-help">Model: <span className="mono">{result.model}</span>{Boolean(result.checked_at) && <> · <Time value={String(result.checked_at)} /></>}</p>{result.error && <ErrorNotice message={errorMessage(result.error)} />}</div>;
}
export function ReadinessPage() {
  const query = useCapabilities(); const saved = useQuery({ queryKey: ["ai-config"], queryFn: aiConfig });
  const [config, setConfig] = useState<AIConfig>(DEFAULTS); const [initialized, setInitialized] = useState(false);
  const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [testId, setTestId] = useState<string>();
  const run = useRun(testId); const router = useRouter(); const client = useQueryClient();
  const finished = Boolean(run.data && TERMINAL.includes(run.data.status)); useRunEvents(testId || "", Boolean(testId), finished);
  useEffect(() => { if (saved.data && !initialized) { const clean = Object.fromEntries(Object.keys(DEFAULTS).map((key) => [key, saved.data[key as keyof AIConfig]])) as unknown as AIConfig; setConfig(clean); setInitialized(true); } }, [initialized, saved.data]);
  useEffect(() => { if (finished) void client.invalidateQueries({ queryKey: ["capabilities"] }); }, [client, finished]);
  const check = run.data?.steps?.find((step) => step.key === "provider_check")?.output as ProviderCheck | undefined;
  const lastCheck = check || query.data?.providers[config.provider]?.last_test;
  async function save() { setBusy("save"); setError(""); setNotice(""); try { await saveAIConfig(config); await client.invalidateQueries({ queryKey: ["ai-config"] }); setNotice("Default model and budgets saved. No model request was made."); } catch (e) { setError(errorMessage(e)); } finally { setBusy(""); } }
  async function test() { setBusy("test"); setError(""); setNotice(""); try { const result = await testAIConfig(config); setTestId(result.run_id || result.job_id); } catch (e) { setError(errorMessage(e)); } finally { setBusy(""); } }
  async function sample() { setBusy("sample"); setError(""); try { const project = await createProject(`Setup sample ${new Date().toISOString()}`); const body = new FormData(); body.set("file", new File([Uint8Array.from(atob(SAMPLE), (c) => c.charCodeAt(0))], "codeagent-sample.zip", { type: "application/zip" })); body.set("project_id", project.id || project.project_id!); body.set("mode", "static"); body.set("profile", "security-v1"); const result = await submitScan(body); router.push(`/jobs/${result.job_id}`); } catch (e) { setError(errorMessage(e)); } finally { setBusy(""); } }
  return <Shell title="Setup" description="Check scanners, configure an optional model, and try a static sample. Credentials stay on the server." action={<button className="button secondary" onClick={() => void query.refetch()}>Refresh status</button>}>
    {query.isPending ? <Loading /> : query.error ? <ErrorNotice message={errorMessage(query.error)} retry={() => void query.refetch()} /> : query.data && <div className="stack">
      <section className="panel"><div className="section-heading"><h2>1. Check scan readiness</h2><Status value={query.data.worker_online ? "online" : "offline"} /></div><p className="muted">{query.data.worker_online ? "The worker is available to process durable scans, connection checks, and reviews." : "Start the worker alongside the API. Saved reports remain available."}</p>{!query.data.auth_required && <p className="field-help">This workspace uses local access. Configure server authentication before sharing it.</p>}<div className="table-scroll"><table><thead><tr><th>Tool</th><th>Availability</th><th>Languages</th><th>Version</th></tr></thead><tbody>{query.data.analyzers.map((tool) => <tr key={tool.name}><td><strong>{tool.name}</strong></td><td><Status value={tool.available ? "available" : "unavailable"} /></td><td>{tool.languages?.join(", ") || "—"}</td><td className="mono">{tool.version || "—"}</td></tr>)}</tbody></table></div>{!query.data.analyzers.length && <Empty title="No analyzers reported" />}{query.data.analyzers.filter((tool) => !tool.available).map((tool) => <p key={tool.name} className="notice warning">{tool.name} is unavailable. Rebuild/start the scanner service and refresh readiness before relying on its coverage.</p>)}{query.data.analyzers.filter((tool) => tool.name === "depcheck" || tool.name === "trivy").map((tool) => { const db = tool.advisory_database; return <p className="field-help" key={tool.name}>Dependency advisory database: {db?.updated_at ? <>updated <Time value={db.updated_at} />{db.age_hours !== undefined && ` (${Math.floor(db.age_hours)} hours old)`}</> : tool.database_age || "freshness unavailable; check scanner database provisioning"}{db?.error && ` · ${db.error}`}</p>; })}</section>
      <section className="panel"><h2>2. Set your review defaults</h2><p className="muted">Static analysis works without a model. These settings apply when you explicitly request AI review.</p>{saved.isPending ? <Loading text="Loading saved settings…" /> : saved.error ? <ErrorNotice message={errorMessage(saved.error)} retry={() => void saved.refetch()} /> : <form onSubmit={(event) => { event.preventDefault(); void save(); }}><ProviderPicker capabilities={query.data} provider={config.provider} model={config.model} onProvider={(provider) => { setConfig((previous) => ({ ...previous, provider, model: modelNames(query.data, provider)[0] || "" })); setTestId(undefined); }} onModel={(model) => { setConfig((previous) => ({ ...previous, model })); setTestId(undefined); }} id="setup" /><div className="field-grid"><div><label htmlFor="min-severity">Review findings at or above</label><select id="min-severity" value={config.min_severity} onChange={(e) => setConfig({ ...config, min_severity: e.target.value as AIConfig["min_severity"] })}>{["critical", "high", "medium", "low"].map((value) => <option key={value}>{value}</option>)}</select></div>{BUDGETS.map((budget) => <div key={budget.key}><label htmlFor={budget.key}>{budget.name}</label><input id={budget.key} type="number" min={budget.min} max={budget.max} required value={config[budget.key]} onChange={(e) => setConfig({ ...config, [budget.key]: Number(e.target.value) })} /></div>)}</div><p className="field-help">One revision is allowed. Budgets also limit interrupted or unsuccessful attempts. Credentials are configured by the administrator, never entered or saved in this form.</p><button className="button primary" disabled={Boolean(busy)}>{busy === "save" ? "Saving…" : "Save defaults"}</button></form>}</section>
      <section className="panel"><div className="section-heading"><h2>3. Verify the model connection</h2>{run.data && <Status value={run.data.status} />}</div><p className="muted">Send a short synthetic structured-output request through the worker. This does not send repository content.{config.provider === "openai" ? " OpenAI usage may incur charges." : " Local mode has no cloud fallback."}</p><CheckResult result={lastCheck?.model === config.model ? lastCheck : { configured: Boolean(config.model && (query.data.providers[config.provider]?.configured ?? query.data.providers[config.provider]?.available)), reachable: query.data.providers[config.provider]?.reachable === true, schema_test_passed: false, model: config.model || "Not selected" }} />{lastCheck?.model !== config.model && <p className="field-help">No saved structured-output test for this selection. Saving settings does not contact a model.</p>}{testId && <p><Link className="text-link" href={`/jobs/${testId}`}>View connection-check run →</Link></p>}{run.data?.error && <ErrorNotice message={run.data.error} />}<button className="button secondary" type="button" disabled={Boolean(busy) || !config.model || !query.data.worker_online || Boolean(testId && !finished)} onClick={() => void test()}>{testId && !finished ? "Checking connection…" : "Test connection"}</button></section>
      <section className="panel"><h2>4. Try a static sample scan</h2><p className="muted">Scan bundled synthetic Python, JavaScript, and dependency examples in a new named sample project. No model call or source execution is involved.</p><button className="button primary" disabled={Boolean(busy) || !query.data.worker_online} onClick={() => void sample()}>{busy === "sample" ? "Submitting sample…" : "Run sample scan"}</button></section>
      {error && <ErrorNotice message={error} />}{notice && <p className="notice neutral" role="status">{notice}</p>}
      <section className="panel"><h2>Supported language coverage</h2><div className="language-list">{query.data.languages.map((language, index) => <span className="pill" key={index}>{typeof language === "string" ? language : language.name || language.language || "Unknown"}</span>)}</div><p className="muted">Each report records the files and rules actually checked. Candidate profile security-v2 remains opt-in until all release gates pass.</p></section>
      <section className="panel"><h2>Private GitHub access</h2><p className="muted">An administrator can configure a repository-scoped, read-only GitHub token on the backend. Enter only the repository URL in the scan form. Scans record the resolved commit and source digest.</p></section>
    </div>}
  </Shell>;
}
